# Generated by Django 4.1.7 on 2023-04-16 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier_name",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "carrier_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("eventId", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "shipping_time",
                    models.DateField(
                        blank=True, null=True, verbose_name="Shipping Time"
                    ),
                ),
                (
                    "order_status_description",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("order_created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateField(blank=True, null=True)),
                (
                    "recipient_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sender_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("updated_at", models.DateField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, max_length=30, null=True)),
                ("destination_country", models.CharField(max_length=20)),
                ("state", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(max_length=20)),
                ("appartment", models.CharField(max_length=20)),
                ("district", models.CharField(blank=True, max_length=20, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("shipped", "Shipped"),
                            ("delivered", "delivered"),
                            ("refunded", "refunded"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("email", models.EmailField(max_length=254)),
                (
                    "order_ship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_shipping",
                        to="Product.products",
                    ),
                ),
                (
                    "recipient_shipping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_product",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_shipping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_product",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
