# Generated by Django 4.1.7 on 2023-04-16 23:40

import Product.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("slug", models.SlugField(max_length=20)),
                ("description", models.CharField(max_length=50)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="Product.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                (
                    "image",
                    models.ImageField(upload_to=Product.models.product_directory_path),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Product.models.product_directory_path,
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Product.models.product_directory_path,
                    ),
                ),
                ("description", models.TextField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sell", "sell"), ("soldout", "soldout")],
                        default="sell",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("views", models.IntegerField(default=0)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("secondhand", models.BooleanField(default=False)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                ("color", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "img_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Product.models.image_thumnail_path,
                    ),
                ),
                (
                    "img2_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Product.models.image_thumnail_path,
                    ),
                ),
                (
                    "img3_thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Product.models.image_thumnail_path,
                    ),
                ),
                (
                    "img_mid",
                    models.ImageField(
                        blank=True, null=True, upload_to=Product.models.image_mid_path
                    ),
                ),
                (
                    "img2_mid",
                    models.ImageField(
                        blank=True, null=True, upload_to=Product.models.image_mid_path
                    ),
                ),
                (
                    "img3_mid",
                    models.ImageField(
                        blank=True, null=True, upload_to=Product.models.image_mid_path
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="Product.category",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "index_together": {("id", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProductViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.CharField(max_length=250)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_views",
                        to="Product.products",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_product_count", models.IntegerField(default=1)),
                (
                    "transaction_type",
                    models.CharField(choices=[(1, "BUY"), (2, "SELL")], max_length=20),
                ),
                ("transaction_description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.products",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProductReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True, default="0", max_length=255, null=True
                    ),
                ),
                ("review", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Product.products",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
